### Project specific config ###

language: go

matrix:
  include:
    - os: linux
      go: "1.13"
      env: ATOM_CHANNEL=stable

    - os: linux
      go: "1.13"
      env: ATOM_CHANNEL=beta

install:
  - go get -u golang.org/x/tools/cmd/gotype

### Generic setup follows ###
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

sudo: false

dist: xenial

addons:
  apt:
    packages:
    - build-essential
    - fakeroot
    - git
    - libsecret-1-dev
    - libgconf-2-4
